### ISSUE TITLE
Formatting not working

### ISSUE THREAD

**Issue by ajmeese7** [jakeboone02/cypher-query-language#1]
Whenever I run "Format Document: on a Cypher document, I get the VS Code popup that there are no formatters installed:

![VS Code formatter error](https://user-images.githubusercontent.com/17814535/199131059-418df424-ff12-4ceb-a510-8b603f8478da.png)

Since the extension README says this is supposed to act as a formatter, I assume that this is an error. Please correct me if I am wrong. Cheers!

**Comment by jakeboone02** [comment]
@ajmeese7 this extension now (as of v2.0.0) has very, very basic formatting capability. Can you upgrade the extension and give it a try?

**Comment by ajmeese7** [comment]
@jakeboone02 It works! I have some thoughts if you're interested:

1. `MATCH (a:Person {uuid: 'abc'}), (b:Person {uuid: '123'})` becomes `MATCH (a:Person { uuid: 'abc' }), (b:Person {uuid: '123'})` (the spacing around the curly braces is only applied to the first item)
2. `foreach(x in coll | delete x)` capitalizes the special words (which is good), but it drops `DELETE x` to the next line. Not sure if this is intended or not, but it is less visually appealing and intuitive IMO

That's all I have noticed so far, my only two Cipher files don't have much to go on unfortunately.

**Comment by jakeboone02** [comment]
Thanks for the feedback! I'll see what I can do about those cases.
