### ISSUE TITLE
Adding syntax highlighting to the Neo4j VS Code Extension

### ISSUE THREAD

**Issue by adam-cowley** [jakeboone02/cypher-query-language#6]
Hey Jake,

I've been hunting around for your contact details but can't find them anywhere.  I've been using this highlighter for years and was wondering if you would be interested in rolling up the changes into [a new extension I've been working on for running Cypher queries in VS Code](https://marketplace.visualstudio.com/items?itemName=adamcowley.neo4j-vscode).

Feel free to email me at adam at neo4j dot com or open a PR if you are interested.

**Comment by jakeboone02** [comment]
See adam-cowley/neo4j-vscode#1. I didn't test it but I think it should work as it's a fairly simple config.

**Comment by adam-cowley** [comment]
Amazing! Thanks for jumping on this so quickly.

**Comment by jakeboone02** [comment]
No problem. (I didn't write the original grammar anyway! `:\` ). Good luck with the extension!
