### ISSUE TITLE
Please consider publishing to the Open VSX Registry

### ISSUE THREAD

**Issue by JDDurrant** [jakeboone02/cypher-query-language#8]
Please consider publishing to the [Open VSX Registry](https://open-vsx.org/).

I use [VSCodium](https://vscodium.com/) because I want to use a _truly_ open source code editor. The official VS Code binaries are proprietary, and they contain analytics code, which invades user privacy and slows the program down.

Unfortunately, due to licensing, only the official VS Code binaries are allowed to download extensions from the Visual Studio Marketplace. Because of this, as a VSCodium user, I depend on the Open VSX Registry for my extensions.

I hope you'll consider publishing your extension there.

**Comment by jakeboone02** [comment]
Honestly, other than some _very_ basic (and buggy) formatting capability in v2.0.0, I haven't done a whole lot of work to produce this extension. The grammar itself was generated using a converter fed with an existing file for an Atom or Sublime extension (I can't remember which).

I'm not going to publish to any other repositories, but feel free to fork this repo and build/publish the extension on your own. You can credit me if you want, but I really wouldn't even care if you didn't.

Also, there's a Neo4j employee working on a more comprehensive extension here: https://github.com/adam-cowley/neo4j-vscode. It already includes the grammar from my extension.

**Comment by JDDurrant** [comment]
@jakeboone02 Cheers. Closing in favour of https://github.com/adam-cowley/neo4j-vscode/issues/3.
